apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
      - name: producer
        image: firemanxbr/veriff:0.1.34
        command: ["python3"]
        args: ["entrypoint.py"]
        volumeMounts:
          - mountPath: "/svc/images/"
            name: task-pv-storage
